home_dir: "/home"

elk_user: "elk"
elk_user_dir: "{{ home_dir }}/{{ elk_user }}"
elk_volumes_dir: "{{ elk_user_dir }}/volumes"
elk_configs_dir: "{{ elk_user_dir }}/configs"
elk_project_name: "elk"

kibana_ip: "127.0.0.1"
kibana_port: "5601"
kibana_image: "kibana:4"
kibana_config_dir: "{{ elk_configs_dir }}/kibana"
kibana_volumes_dir: "{{ elk_volumes_dir }}/kibana"
kibana_dhparam_dir: "{{ kibana_config_dir }}/dhparam"
kibana_nginx_template: "kibana.nginx.conf.j2"
kibana_nginx_config_file: "/etc/nginx/conf.d/{{ kibana_server_name }}.conf"
kibana_ssl_certificate: "/etc/letsencrypt/live/{{ kibana_server_name }}/fullchain.pem"
kibana_ssl_certificate_key: "/etc/letsencrypt/live/{{ kibana_server_name }}/privkey.pem"

elasticsearch_image: "elasticsearch:2"
elasticsearch_config_dir: "{{ elk_configs_dir }}/elasticsearch"
elasticsearch_volumes_dir: "{{ elk_volumes_dir }}/elasticsearch"
elasticsearch_data_dir: "{{ elasticsearch_volumes_dir }}/data"
elasticsearch_volume_config_dir: "{{ elasticsearch_volumes_dir }}/config"
elasticsearch_scripts_dir: "{{ elasticsearch_volume_config_dir }}/scripts"
elasticsearch_config: "elasticsearch.yaml.j2"
elasticsearch_config_file: "{{ elasticsearch_volume_config_dir }}/elasticsearch.yaml"

dockerbeat_image: "ingensi/dockerbeat:latest"
dockerbeat_volumes_dir: "{{ elk_volumes_dir }}/elasticsearch"
dockerbeat_data_dir: "{{ dockerbeat_volumes_dir }}/data"
dockerbeat_config: "dockerbeat.yml.j2"
dockerbeat_config_file: "{{ dockerbeat_data_dir }}/dockerbeat.yml"
dockerbeat_template: "dockerbeat.template.json.j2"
dockerbeat_template_file: "{{ dockerbeat_data_dir }}/dockerbeat.template.json"

elk_dirs:
  - "{{ elk_volumes_dir }}"
  - "{{ elk_configs_dir }}"
  - "{{ kibana_config_dir }}"
  - "{{ kibana_volumes_dir }}"
  - "{{ kibana_dhparam_dir }}"
  - "{{ elasticsearch_config_dir }}"
  - "{{ elasticsearch_volumes_dir }}"
  - "{{ elasticsearch_data_dir }}"
  - "{{ elasticsearch_volume_config_dir }}"
  - "{{ elasticsearch_scripts_dir }}"
  - "{{ dockerbeat_volumes_dir }}"
  - "{{ dockerbeat_data_dir }}"
